import Head from "next/head";
import Link from "next/link";
import {
  Contact,
  GithubIcon,
  FacebookIcon,
  LinkedinIcon,
  Heading,
} from "../styles/styles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Johannes Osterkamp - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading>Johannes Osterkamp</Heading>
      <Contact>
        <Link href="https://github.com/HannesOster">
          <GithubIcon />
        </Link>
        <Link href="https://www.linkedin.com/in/johannes-osterkamp-a30731238/">
          <LinkedinIcon />
        </Link>
        <Link href="https://www.facebook.com/johannes.osterkamp.3">
          <FacebookIcon />
        </Link>
      </Contact>

      <p>
        Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
        Lorem ipsum dolor
      </p>
    </>
  );
}
